CREATE TABLE IF NOT EXISTS public.passkeys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  filter_by_type jsonb DEFAULT NULL,
  filter_by_location jsonb DEFAULT NULL,
  filter_by_owner jsonb DEFAULT NULL,
  allowed_databases text DEFAULT 'msme_registry',
  created_at timestamptz DEFAULT now(),
  is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.passkey_filters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passkey_id bigint REFERENCES public.passkeys(id) ON DELETE CASCADE,
  filter_type text NOT NULL,
  filter_value text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.passkey_items (
  passkey_id bigint REFERENCES public.passkeys(id) ON DELETE CASCADE,
  business_number text NOT NULL,
  PRIMARY KEY (passkey_id, business_number)
);

ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS filter_by_type jsonb DEFAULT NULL;
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS filter_by_location jsonb DEFAULT NULL;
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS filter_by_owner jsonb DEFAULT NULL;
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS allowed_databases text DEFAULT 'msme_registry';
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

ALTER TABLE public.passkeys DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.passkey_filters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.passkey_items DISABLE ROW LEVEL SECURITY;
