-- Create passkeys table if it doesn't exist
-- Finalized Passkey Schema for Supabase
-- This script sets up tables to match the logic in admin.html

-- 1. The main definitions table
CREATE TABLE IF NOT EXISTS public.passkeys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE, -- Crucial for UPSERT onConflict logic and passkey identification
    filter_by_type jsonb DEFAULT NULL,
    filter_by_location jsonb DEFAULT NULL,
    filter_by_owner jsonb DEFAULT NULL,
    allowed_databases text DEFAULT 'msme_registry',
    created_at timestamptz DEFAULT now(),
    is_active boolean DEFAULT true
);

-- CREATE TABLE IF NOT EXISTS does not update older tables, so add new columns explicitly.
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS filter_by_type jsonb DEFAULT NULL;
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS filter_by_location jsonb DEFAULT NULL;
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS filter_by_owner jsonb DEFAULT NULL;
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS allowed_databases text DEFAULT 'msme_registry';
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.passkeys ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- 2. Generic filter table (as described by user)
-- This table allows for more flexible key-value pair filtering if needed in the future.
CREATE TABLE IF NOT EXISTS public.passkey_filters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passkey_id bigint REFERENCES public.passkeys(id) ON DELETE CASCADE, -- Automatically cleans up filters
    filter_type text NOT NULL,
    filter_value text, -- Using text for generic values, can be JSON stringified if needed
    created_at timestamptz DEFAULT now()
);

-- 3. The junction table for associated businesses
CREATE TABLE IF NOT EXISTS public.passkey_items (
    passkey_id bigint REFERENCES public.passkeys(id) ON DELETE CASCADE,
    business_number text NOT NULL, -- Must match the type of your businesses.number
    PRIMARY KEY (passkey_id, business_number)
);

-- 3. Disable RLS for unrestricted access as requested
ALTER TABLE public.passkeys DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.passkey_filters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.passkey_items DISABLE ROW LEVEL SECURITY;
